name: check-availability

on:
  push:
#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    - cron:  '*/10 * * * *'

jobs:
  check-availability:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.5' # The Go version to download (if necessary) and use.
      - name: Go Modules
        run: go mod download
        env:
          GO111MODULE: "on"
      - name: run the script
        run: go run main.go
        env:
          TELEGRAM_ENABLED: "true"
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
